kind = "web"
previewPath = "/"
title = "MATRIX Website"
version = "1.0.0"
id = "artifacts/matrix-website"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25482

[services.development]
run = "pnpm --filter @workspace/matrix-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/matrix-website", "run", "build" ]
serve = "static"
publicDir = "artifacts/matrix-website/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25482"
BASE_PATH = "/"
